### PR TITLE
Add `stale-closer` bot that uses mostly code from `feature-request` bot

### PR DESCRIPTION
**Pull request by bwateratmsft**
This can fulfill the role from https://github.com/microsoft/vscode-azuretools/tree/main/triage-actions.

### CODE REVIEW

**Comment by JacksonKearl** [comment]
Cool, thanks!

**Comment by bwateratmsft** [comment]
@JacksonKearl thanks! How often does the `stable` tag get bumped?

**Comment by JacksonKearl** [comment]
It's manual, would you like me to bump it?

**Comment by bwateratmsft** [comment]
As long as we're confident I haven't regressed anything, sure!

**Comment by JacksonKearl** [comment]
bumped stable

**Pull request merged**
