### PR TITLE
Add Github actions for Python related extensions

### PR DESCRIPTION
**Pull request by karrtikr**
For https://github.com/microsoft/vscode-python/issues/21110

### CODE REVIEW

**Comment by lramos15** [comment]
I'm not sure I follow why we need all this extra stuff, is this not something we can accomplish with the commands syntax that the core VS Code repo uses?

https://github.com/microsoft/vscode/blob/main/.github/commands.json

**Comment by karrtikr** [comment]
This is just transitioning all existing Github actions in [vscode-python](https://github.com/microsoft/vscode-python) to this repo instead of creating a new one. For any new actions we add we can use the existing syntax where applicable. I would like to keep code as it is for simplicity.

We initially created https://github.com/microsoft/vscode-python-engineering but were suggested to add them in this repo instead.

**Comment by lramos15** [comment]
It feels a bit strange that a lot of this code just duplicates existing functionality we have though, you could avoid having to maintain a new set of code by adopting the same patterns that VS Code core does.

**Review by lramos15 — CHANGES_REQUESTED** [review]
Please rename the `triage-info-needed` folder to have a python prefix as well so we know it's for the python repo as we already have some triager code here and I don't want there to be confusion between the two.

**Comment by karrtikr** [comment]
I don't expect existing actions to be changing too much, hence I do not think it will be worth it. Python extension can own all these actions so as to not interfere, and for any new actions or modifications we can make the transition to use patterns used by VSCode core.

**Review by lramos15 — APPROVED** [review]

**Pull request merged**
